<a href="https://colab.research.google.com/github/paulgilbert6/test/blob/main/Copie_de_Machine_Learning_Paris_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [103]:
import pandas as pd
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

In [4]:
df = pd.read_csv("ML_Paris24.csv")
df.head(1)

game_year    country  total_medal gdp_per_capita     population  \
0       1996  Argentina            3      15,570.00  35,389,360.00   

   democracy_index  host_city  last_score   log_gdp    log_pop  
0             0.83          0           0  9.653101  17.381922

In [5]:
df['previous_olympics'] = df.game_year - 4

In [6]:
df.head()

game_year     country  total_medal gdp_per_capita     population  \
0       1996   Argentina            3      15,570.00  35,389,360.00   
1       1996   Australia           41      34,960.00  18,211,850.00   
2       1996  Azerbaijan            1       2,625.00   7,949,107.00   
3       1996     Belarus           15       8,840.00  10,436,455.00   
4       1996     Belgium            6      28,905.00  10,123,230.00   

   democracy_index  host_city  last_score    log_gdp    log_pop  \
0             0.83          0           0   9.653101  17.381922   
1             0.89          0           0  10.461960  16.717583   
2             0.24          0           0   7.872836  15.888570   
3             0.45          0           0   9.087042  16.160816   
4             0.88          0           0  10.271770  16.130343   

   previous_olympics  
0               1992  
1               1992  
2               1992  
3               1992  
4               1992

In [7]:
df.isnull().sum()

game_year            0
country              0
total_medal          0
gdp_per_capita       0
population           0
democracy_index      0
host_city            0
last_score           0
log_gdp              0
log_pop              0
previous_olympics    0
dtype: int64

In [90]:
df_train, df_test = train_test_split(df, test_size=0.2, random_state=42, shuffle=True)

In [91]:
reg = LinearRegression()
# X_train = df_train[["log_gdp", "log_pop", "democracy_index", "last_score", "host_city", "previous_olympics"]]
X_train = df_train[["last_score", "previous_olympics"]]
y_train = df_train[["total_medal"]]
reg.fit(X_train, y_train)

LinearRegression()

In [10]:
reg.intercept_

array([752.06227584])

In [11]:
reg.coef_

array([[ 0.97990597, -0.37353871]])

In [49]:
reg.score(X_train, y_train)

0.7602109034332252

In [ ]:
import statsmodels.api as sm
import numpy as np
X = X_train
X = sm.add_constant(X)
model = sm.OLS(y_train, X)
results = model.fit()
results.params

const                702.649665
last_score             0.942697
previous_olympics     -0.348883
dtype: float64

In [ ]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:            total_medal   R-squared:                       0.777
Model:                            OLS   Adj. R-squared:                  0.775
Method:                 Least Squares   F-statistic:                     491.3
Date:                Tue, 05 Sep 2023   Prob (F-statistic):           1.28e-92
Time:                        07:51:09   Log-Likelihood:                -1069.2
No. Observations:                 285   AIC:                             2144.
Df Residuals:                     282   BIC:                             2155.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const               702.6497    157.39

In [ ]:
y_pred = reg.predict(X_train)
r2_score(y_train, y_pred)

0.7770159833914356

In [ ]:
X_test = df_test[["last_score", "previous_olympics"]]
y_test = df_test[["total_medal"]]
y_test_pred = reg.predict(X_test)
print(f"Predicted values for the test set: {y_test_pred}")

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_test_pred)

6.002846264038126

In [13]:
df.head(1)

game_year    country  total_medal gdp_per_capita     population  \
0       1996  Argentina            3      15,570.00  35,389,360.00   

   democracy_index  host_city  last_score   log_gdp    log_pop  \
0             0.83          0           0  9.653101  17.381922   

   previous_olympics  
0               1992

In [89]:
kf = KFold(n_splits=5)

In [130]:
reg2 = LinearRegression()
X_train2 = df_train[["democracy_index","host_city","last_score", "log_gdp", "log_pop", "previous_olympics"]]
y_train2 = df_train[["total_medal"]]
reg2.fit(X_train2, y_train2)

LinearRegression()

In [126]:
X = X_train2.to_numpy()

In [127]:
y = y_train2.to_numpy()

In [128]:
mse_scores = []
for train_index, test_index in kf.split(X):
    X_train2, X_test2 = X[train_index], X[test_index]
    y_train2, y_test2 = y[train_index], y[test_index]
    reg2.fit(X_train2, y_train2)
    y_pred2 = reg2.predict(X_test2)
    mse_scores.append(mean_squared_error(y_test2, y_pred2))

In [106]:
mse_scores

[93.83835730099491,
 52.38156624244614,
 59.241903596402736,
 65.9021878021357,
 269.57342400194324]

In [107]:
reg2.score(X_train2, y_train2)

0.8516537360743089

In [108]:
y_pred2 = reg2.predict(X_train2)
r2_score(y_train2, y_pred2)

0.8516537360743089

In [131]:
X_test_France2 = [[0.872, 1, 33, 17.983, 10.7143, 2020]]

In [132]:
reg2.predict(X_test_France2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[62.79827497]])

In [64]:
X_test_France = [[33, 2020]]

In [65]:
reg.predict(X_test_France)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[28.40548123]])

In [57]:
reg3 = LinearRegression()
X_train3 = df_train[["democracy_index","last_score", "log_gdp", "log_pop", "previous_olympics"]]
y_train3 = df_train[["total_medal"]]
reg3.fit(X_train3, y_train3)

LinearRegression()

In [58]:
reg3.score(X_train3, y_train3)

0.7937049596362731

In [59]:
X_test_France3 = [[0.872, 33, 17.983, 10.7143, 2020]]

In [60]:
reg3.predict(X_test_France3)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[36.27568759]])

In [68]:
X_test_GB2 = [[0.862, 0, 65, 18.0244, 10.714, 2020]]

In [69]:
reg2.predict(X_test_GB2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[61.80759359]])

In [72]:
X_test_United_States2 = [[0.813, 0, 113, 19.636, 11.0615, 2020]]

In [73]:
reg2.predict(X_test_United_States2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[107.25886332]])

In [74]:
X_test_China2 = [[0.77, 0, 88, 21.0781, 9.776, 2020]]

In [75]:
reg2.predict(X_test_China2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[89.20377301]])

In [76]:
X_test_Russia2 = [[0.252, 0, 70, 18.7965, 10.239, 2020]]

In [77]:
reg2.predict(X_test_Russia)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[69.47151535]])

In [78]:
X_test_Japan2 = [[0.838, 0, 57, 18.641, 10.61605, 2020]]

In [79]:
reg2.predict(X_test_Japan2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[57.54901986]])

In [80]:
X_test_Australia2 = [[0.849, 0, 45, 17.071, 10.81525, 2020]]

In [81]:
reg2.predict(X_test_Australia2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[42.63840703]])

In [82]:
X_test_Netherlands2 = [[0.863, 0, 36, 16.678, 10.9441, 2020]]

In [83]:
reg2.predict(X_test_Netherlands2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[34.31682928]])

In [84]:
X_test_Italy2 = [[0.849, 0, 40, 17.897, 10.644, 2020]]

In [85]:
reg2.predict(X_test_Italy2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[41.25912773]])

In [86]:
X_test_Germany2 = [[0.872, 0, 37, 18.2393, 10.88144, 2020]]

In [87]:
reg2.predict(X_test_Germany2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[40.75415989]])

In [135]:
df2 = pd.read_csv('ML_Paris2024_v2.csv')

In [138]:
df2 = df2[df2['game_year']==2024]

In [ ]:
test2 = df2[df2["game_year"]==2024].country
test2

In [ ]:
df2

In [144]:
df3 = df2.drop(columns=["game_year","country","total_medal","gdp_per_capita","population"])

In [ ]:
df3

In [146]:
df3["previous_edition"] = 2020
df3

democracy_index  host_city  last_score  log_gdp  log_pop  \
357             0.86          0          45   11.076   17.090   
358             0.68          0          20    9.232   19.193   
359             0.85          0          24   10.901   17.473   
360             0.87          1          33   10.730   17.986   
361             0.86          0          37   10.878   18.238   
362             0.84          0          65   10.806   18.031   
363             0.45          0          20    9.948   16.134   
364             0.84          0          40   10.536   17.891   
365             0.83          0          57   10.505   18.630   
366             0.85          0          36   11.065   16.684   
367             0.89          0          20   10.786   15.470   
368             0.07          0          88    9.602   21.078   
369             0.81          0          20   10.458   17.763   
370             0.21          0          70    9.604   18.788   
371             0.87          0          17   10.389   17.677   
372             0.41          0          19    8.445   17.420   
373             0.82          0         113   11.316   19.644   

     previous_edition  
357              2020  
358              2020  
359              2020  
360              2020  
361              2020  
362              2020  
363              2020  
364              2020  
365              2020  
366              2020  
367              2020  
368              2020  
369              2020  
370              2020  
371              2020  
372              2020  
373              2020

In [147]:
test = df3.to_numpy()

In [148]:
test

array([[8.6000e-01, 0.0000e+00, 4.5000e+01, 1.1076e+01, 1.7090e+01,
        2.0200e+03],
       [6.8000e-01, 0.0000e+00, 2.0000e+01, 9.2320e+00, 1.9193e+01,
        2.0200e+03],
       [8.5000e-01, 0.0000e+00, 2.4000e+01, 1.0901e+01, 1.7473e+01,
        2.0200e+03],
       [8.7000e-01, 1.0000e+00, 3.3000e+01, 1.0730e+01, 1.7986e+01,
        2.0200e+03],
       [8.6000e-01, 0.0000e+00, 3.7000e+01, 1.0878e+01, 1.8238e+01,
        2.0200e+03],
       [8.4000e-01, 0.0000e+00, 6.5000e+01, 1.0806e+01, 1.8031e+01,
        2.0200e+03],
       [4.5000e-01, 0.0000e+00, 2.0000e+01, 9.9480e+00, 1.6134e+01,
        2.0200e+03],
       [8.4000e-01, 0.0000e+00, 4.0000e+01, 1.0536e+01, 1.7891e+01,
        2.0200e+03],
       [8.3000e-01, 0.0000e+00, 5.7000e+01, 1.0505e+01, 1.8630e+01,
        2.0200e+03],
       [8.5000e-01, 0.0000e+00, 3.6000e+01, 1.1065e+01, 1.6684e+01,
        2.0200e+03],
       [8.9000e-01, 0.0000e+00, 2.0000e+01, 1.0786e+01, 1.5470e+01,
        2.0200e+03],
       [7.0000e-02, 0

array([8.6000e-01, 0.0000e+00, 4.5000e+01, 1.1076e+01, 1.7090e+01,
       2.0200e+03])

In [161]:
countries = df2.country.unique().tolist()
countries

['Australia',
 'Brazil',
 'Canada',
 'France',
 'Germany',
 'Great Britain',
 'Hungary',
 'Italy',
 'Japan',
 'Netherlands',
 'New Zealand',
 "People's Republic of China",
 'Republic of Korea',
 'Russian Federation',
 'Spain',
 'Ukraine',
 'United States of America']

In [171]:
for country in range(len(countries)):
  value = countries[country]
  print(f'the total medal for {value} is : {reg2.predict([test[country]]).round(0)}')

the total medal for Australia is : [[38.]]
the total medal for Brazil is : [[17.]]
the total medal for Canada is : [[22.]]
the total medal for France is : [[55.]]
the total medal for Germany is : [[34.]]
the total medal for Great Britain is : [[56.]]
the total medal for Hungary is : [[13.]]
the total medal for Italy is : [[34.]]
the total medal for Japan is : [[50.]]
the total medal for Netherlands is : [[30.]]
the total medal for New Zealand is : [[13.]]
the total medal for People's Republic of China is : [[80.]]
the total medal for Republic of Korea is : [[18.]]
the total medal for Russian Federation is : [[59.]]
the total medal for Spain is : [[15.]]
the total medal for Ukraine is : [[10.]]
the total medal for United States of America is : [[100.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature n

In [155]:
for country in range(len(countries)):
  print(country)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [176]:
df_test3 = df3
df_test3.head(1)

democracy_index  host_city  last_score  log_gdp  log_pop  \
357             0.86          0          45   11.076    17.09   

     previous_edition  
357              2020

In [177]:
df_test4 = df_test3[["log_gdp", "democracy_index", "host_city", "last_score", "previous_edition"]]
df_test4

log_gdp  democracy_index  host_city  last_score  previous_edition
357   11.076             0.86          0          45              2020
358    9.232             0.68          0          20              2020
359   10.901             0.85          0          24              2020
360   10.730             0.87          1          33              2020
361   10.878             0.86          0          37              2020
362   10.806             0.84          0          65              2020
363    9.948             0.45          0          20              2020
364   10.536             0.84          0          40              2020
365   10.505             0.83          0          57              2020
366   11.065             0.85          0          36              2020
367   10.786             0.89          0          20              2020
368    9.602             0.07          0          88              2020
369   10.458             0.81          0          20              2020
370    9.604             0.21          0          70              2020
371   10.389             0.87          0          17              2020
372    8.445             0.41          0          19              2020
373   11.316             0.82          0         113              2020